# Generated by Django 3.0.3 on 2020-02-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
